dist: xenial
language: python
jobs:
    include:
        - name: "PyBML test on Xenial Linux with Python 3.7"
          python: 3.7
install: pip3 install -r requirements.txt
script: cd train_script
script: python3 maml_train.py
