dist: xenial
language: python
after_success:
    - bash <(curl -s https://codecov.io/bash)
jobs:
    include:
        - name: "PyBML test on Xenial Linux with Python 3.7"
          python: 3.7
install: 
    - pip3 install -r requirements.txt
    - pip install coverage
script: 
    - cd train_script
    # - python3 maml_train.py
    - coverage run maml_train.py
