coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.2
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        # basic
        target: auto
        threshold: 0.2
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
        
ignore:
    # ignore the base calsses which will be automatically inherited.
  - "boml/optimizer/opt.py"
  - "boml/setup_model/network.py"
  - "boml/upper_iter/outer_grad.py"
  - "boml/setup_model/network_utils.py"
  - "test/script_helper.py"
  - "boml/load_data/**/*"
  - "boml/extension.py"
